services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: instructphp-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: instructphp-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    container_name: instructphp-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./storage/preload:/sqldata
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306